#!/usr/bin/bash

Help () {
  echo "Usage: $(basename $0) [-l LIBRARY_NAME] PROJECT_NAME"
  echo "Create a C++ project with PROJECT_NAME."
  echo "You can add a library (.h and .cc files) using the -l option."
  exit 1
}

if [ $# -lt 1 ]; then
  Help
fi

while getopts "l:" option; do
  case "${option}" in
    l)
      lib="${OPTARG}"
      ;;
    ?)
      Help
      ;;
  esac
done

shift "$(($OPTIND - 1))"
mkdir "${1}"
cd "${1}"

shopt -s extglob
if [ ${lib} ]; then
  cp ~/.cppt/* "${PWD}"
else 
  cp ~/.cppt/!(functions.*) "${PWD}"
fi

mv template.cc "${1}.cc"
sed -i "4s/.*/MAIN = ${1}/" Makefile
sed -i "8s/.*/  * @date $(date +'%b %d %Y')/" "${1}.cc"

if [ ${lib} ]; then
  mv functions.cc "${lib}.cc"
  mv functions.h "${lib}.h"
  sed -i "8s/.*/  * @date $(date +'%b %d %Y')/" "${lib}.cc"
  sed -i "14s/.*/#include \"${lib}.h\"/" "${lib}.cc"
  sed -i "16s/.*/#include \"${lib}.h\"\n/" "${1}.cc"
  sed -i "8s/.*/  * @date $(date +'%b %d %Y')/" "${lib}.h"
  sed -i "5s/\$(MAIN).o/\$(MAIN).o ${lib}.o/" Makefile
fi
